### ISSUE TITLE
CVSS Calculator

### ISSUE THREAD

**Issue by BuffaloWill** [SerpicoProject/SerpicoPlugins#1]
A neat feature would be a risk calculator, so you could assign risk to a finding. If for example, you're using DREAD or CVSS, you could have a side calculator that you could plug in the appropriate risk metrics, and output the score.

Something similar to this: https://nvd.nist.gov/CVSS/v3-calculator

From https://github.com/SerpicoProject/Serpico/issues/194

**Comment by pentestgou1** [comment]
Has this already been implemented?

**Comment by BuffaloWill** [comment]
This is landed in master.
